server/ServerMVC/Controllers/AnalysisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic.FileIO;
using ServerMVC.Infrastructure.Statistics;
using System.Globalization;

namespace ServerMVC.Controllers
{
    public class AnalysisController : Controller
    {

        //IWebHostEnvironment _appEnvironment;
        //public AnalysisController(IWebHostEnvironment appEnvironment)
        //{
        //    _appEnvironment = appEnvironment;
        //}
        public IActionResult Index()
        {
            ViewBag.Title = "Анализ";
            return View();
        }
        public OneFactorData[] RangeData(OneFactorData[] d)
        {
            Dictionary<double, double> monolithRankedArray = new Dictionary<double, double>();
            int n = 0;
            foreach (OneFactorData o in d)
                n += o.Length;
            double[] monolithSortedArr = new double[n];
            int cntr = 0;
            for (int i = 0; i < d.Length; i++)
            {
                for (int j = 0; j < d[i].Length; j++)
                {
                    monolithSortedArr[cntr] = d[i][j];
                    cntr++;
                }
            }
            Array.Sort(monolithSortedArr);
            int rnk = 1;
            double tmp = rnk;
            double k = 1;
            for (int i = 0; i < monolithSortedArr.Length; i++)
            {
                if (i != monolithSortedArr.Length - 1 && monolithSortedArr[i] == monolithSortedArr[i + 1])
                {
                    rnk++;
                    tmp += rnk;
                    k++;
                }
                else
                {
                    monolithRankedArray.Add(monolithSortedArr[i], tmp / k);
                    k = 1;
                    rnk++;
                    tmp = rnk;
                }
            }

            OneFactorData[] rankedData = new OneFactorData[d.Length];
            for (int i = 0; i < d.Length; i++)
            {
                double[] rankedArr = new double[d[i].Length];
                for (int j = 0; j < d[i].Length; j++)
                {
                    rankedArr[j] = monolithRankedArray[d[i][j]];
                }
                OneFactorData rankedGroup = new OneFactorData(rankedArr);
                rankedData[i] = rankedGroup;
            }
            return rankedData;
        }
        [HttpGet]
        public PartialViewResult _SpawnAnalyze(string inputData)
        {
            if (inputData == null)
                return PartialView("_SpawnAnalyze", null);
            string[] strGroups = inputData.Split(new char[] { '\n' });
            OneFactorData[] inputAnovaData = new OneFactorData[strGroups.Length];
            int i = 0;
            IFormatProvider formatter = new NumberFormatInfo { NumberDecimalSeparator = "." };
            foreach (string strGroup in strGroups)
            {
                List<double> listObservations = new List<double>();
                string[] strObs = strGroup.Split(new char[] { ',' });
                foreach(string s in strObs)
                {
                    if (double.TryParse(s, NumberStyles.AllowDecimalPoint, formatter, out double number))
                        listObservations.Add(number);
                    else 
                        return PartialView("_SpawnAnalyze", null);

                }
                double[] observations = listObservations.ToArray();
                inputAnovaData[i] = new OneFactorData(observations);
                i++;
            }
            Anova anova = new Anova(inputAnovaData);
            Anova nonParametricAnova = new Anova(RangeData(inputAnovaData));
            anova.Frnk = nonParametricAnova.F;
            anova.Prnk = nonParametricAnova.p;
            return PartialView("_SpawnAnalyze", anova);
        }
        //[HttpPost]
        //public async Task<PartialViewResult> _UploadData(IFormFile upload)
        //{
        //    List<string[]> dataForTable = new List<string[]>();
        //    if (upload != null && Path.GetExtension(upload.FileName) == ".csv")
        //    {
        //        string path = _appEnvironment.WebRootPath + "\\Files\\" + upload.FileName;
        //        using (var fileStream = new FileStream(path, FileMode.Create))
        //        {
        //            await upload.CopyToAsync(fileStream);
        //        }
        //        using (TextFieldParser tfp = new TextFieldParser(path))
        //        {
        //            tfp.TextFieldType = FieldType.Delimited;
        //            tfp.SetDelimiters(",");
        //            while (!tfp.EndOfData)
        //            {
        //                string[] fields = tfp.ReadFields();
        //                dataForTable.Add(fields);
        //            }
        //        }
        //    }
        //    return PartialView(dataForTable);
        //}
        public ActionResult Header() => PartialView("_Header");
        public ActionResult Footer() => PartialView("_Footer");
    }
}

server/ServerMVC/Controllers/FieldMapController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.ObjectPool;
using ServerMVC.Controllers;
using ServerMVC.Models;
using ServerMVC.Models.Repository;

namespace ServerMVC.Controllers
{
    public class FieldMapController : Controller
    {
        private readonly IMoistmeterRepository _moistmeterRepository;
        public FieldMapController(IMoistmeterRepository moistRepo)
        {
            _moistmeterRepository = moistRepo;
        }
        public List<object> IncarnateMoistMeasurement(DateTime startDate, int sensorName)
        {
            List<object> temperatureChart = new List<object>();
            List<string> labels = new List<string>();
            List<double> valuesChan1 = new List<double>();
            List<double> valuesChan2 = new List<double>();
            List<double> valuesChan3 = new List<double>();
            List<double> valuesChan4 = new List<double>();
            List<double> valuesChan5 = new List<double>();
            IQueryable<IGrouping<int, agro_moist>> lookup;
            startDate = startDate.ToUniversalTime();
            if (sensorName != 0)
                lookup = _moistmeterRepository.Moistmeters.Where(p => p.reg_date == startDate && p.sensor == sensorName).GroupBy(p => p.reg_date.Hour);
            else
                lookup = _moistmeterRepository.Moistmeters.Where(p => p.reg_date == startDate).GroupBy(p => p.reg_date.Hour);
            var tmp = lookup.ToList();
            foreach (var j in tmp)
            {
                int year = j.Select(p => p.reg_date.Year).First();
                int month = j.Select(p => p.reg_date.Month).First();
                int day = j.Select(p => p.reg_date.Day).First();
                int hour = j.Select(p => p.reg_date.Hour).First();
                DateTime outDate = new DateTime(year, month, day, hour, 0, 0);
                string outStrDate = outDate.ToString("MM-dd HH:mm");
                double chan1val = j.Select(p => p.m1).First();
                double chan2val = j.Select(p => p.m2).First();
                double chan3val = j.Select(p => p.m3).First();
                double chan4val = j.Select(p => p.m4).First();
                double chan5val = j.Select(p => p.m5).First();
                labels.Add(outStrDate);
                valuesChan1.Add(chan1val);
                valuesChan2.Add(chan2val);
                valuesChan3.Add(chan3val);
                valuesChan4.Add(chan4val);
                valuesChan5.Add(chan5val);
            }
            temperatureChart.Add(labels);
            temperatureChart.Add(valuesChan1);
            temperatureChart.Add(valuesChan2);
            temperatureChart.Add(valuesChan3);
            temperatureChart.Add(valuesChan4);
            temperatureChart.Add(valuesChan5);
            return temperatureChart;
        }
        [HttpGet]
        public List<object> GetData(DateTime date, int sensorName)
        {
            return IncarnateMoistMeasurement(date.ToUniversalTime(), sensorName);
        }
        [HttpGet]
        public PartialViewResult _GetMoistmeterTable(DateTime date, int sensorName)
        {
            if (sensorName != null)
                return PartialView(_moistmeterRepository.Moistmeters.Where(p => p.reg_date == date.ToUniversalTime() && p.sensor == sensorName));
            return PartialView(_moistmeterRepository.Moistmeters.Where(p => p.reg_date == date.ToUniversalTime()));
        }
        public ViewResult Index() 
        {
            ViewBag.Title = "Датчики"; 
            return View(); 
        }
        public ActionResult Header() => PartialView("_Header");
        public ActionResult Footer() => PartialView("_Footer");
    }
}

server/ServerMVC/Views/Shared/_Footer.cshtml
<h1 class="visually-hidden">Контакты</h1>
<div class="main-footer__wrapper">
    <p class="main-footer__address">Поле Меньково blockhin@email.ru</p>
    <a asp-controller="Home" asp-action="Index">
        <img class="ari-logo" src="/img/agrophysLogo.png" alt="Логотип АФИ">
    </a>
    <p class="main-footer__about">Программа разработана в 170 отделе ФГБНУ АФИ</p>
</div>

server/ServerMVC/Views/Shared/_Header.cshtml
<div class="main-header__top main-header__top--closed main-header__top--nojs">
    <button class="main-header__top__toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
    @{
        //DateTime.Now.ToString("yyyy-MM-dd")
        var calendar = Html.TextBox("Name", "2024-05-06", new { @class = "main-header__calendar site-list__item", @type = "date", @id = "calendar", @name = "calendarInput" });
    }
    @calendar
    <input class="main-header__button sample-button site-list__item" type="submit" onclick="location.href='@Url.Action("Index", "Home")'" value="Главная" />
    @* <input class="main-header__calendar" type="date" id="calendar" name="calendarInput" value="2023-10-27"> *@
    <input class="main-header__button sample-button site-list__item" type="submit" onclick="location.href='@Url.Action("Index", "FieldMap")'" value="Датчики" />
    
    @* <a class="ari-logo-link main-header__logo-link" asp-controller="Home" asp-action="Index">
        <img class="ari-logo" src="/img/agrophysLogo.png" alt="Логотип АФИ">
    </a> *@
    <input class="main-header__button sample-button site-list__item" type="submit" onclick="location.href='@Url.Action("Index", "Analysis")'" value="Анализ" />
    @if (!User.Identity.IsAuthenticated)
    {
        <button class="main-header__button sample-button site-list__item" onclick="location.href='@Url.Action("Register", "Account")'">Регистрация</button>
        <button class="main-header__button sample-button site-list__item" onclick="location.href='@Url.Action("Login", "Account")'">Войти</button>
    }
    @if (User.Identity.IsAuthenticated)
    {
        <div class="main-header__user-greeteng site-list__item"><p>Добрый день, @User.Identity.Name</p></div>
        <form method="post" asp-controller="Account" asp-action="Logout">
            <input class="sample-button" type="submit" value="Выход" />
        </form>
    }
</div>
<img class="main-header__fieldimg" src="/img/dayOfTheField.png" alt="День поля">

server/ServerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @* <link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" /> *@
    <link rel="stylesheet" href="/css/style.css">
    <script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body class="page__body">
    @RenderBody()
    <script src="/js/mobileheadermenu.js" type="text/javascript"></script>
</body>
</html>